import { StrategyConfig } from "@/types/strategy";
import { Card } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Copy, Download, Code2 } from "lucide-react";
import { toast } from "sonner";

interface Props {
  config: StrategyConfig;
}

export const CodeGeneratorStep = ({ config }: Props) => {
  const generateMQL5 = () => {
    return `//+------------------------------------------------------------------+
//|                                    Quantum Strategy EA           |
//|                                    Generated by Strategy Builder |
//+------------------------------------------------------------------+
#property copyright "Quantum Strategy Builder"
#property version   "1.00"
#property strict

// Input Parameters
input double RiskPercent = ${config.positionSizePercent};
input double StopLossPips = ${config.stopLoss.pips || 10};
input double TakeProfitRatio = ${config.takeProfit.ratio || 2};
input int MaxDailyLoss = ${config.maxDailyLoss};

// Indicator Handles
${config.indicators
  .map((ind) => {
    if (ind.type === "EMA") return `int handle_ema_${ind.params.period};`;
    if (ind.type === "RSI") return `int handle_rsi;`;
    if (ind.type === "MACD") return `int handle_macd;`;
    return "";
  })
  .join("\n")}

// Global Variables
double dailyPnL = 0.0;
datetime lastTradeDate = 0;

//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
{
   // Initialize indicators
${config.indicators
  .map((ind) => {
    if (ind.type === "EMA")
      return `   handle_ema_${ind.params.period} = iMA(_Symbol, PERIOD_${config.timeframe.toUpperCase()}, ${ind.params.period}, 0, MODE_EMA, PRICE_CLOSE);`;
    if (ind.type === "RSI")
      return `   handle_rsi = iRSI(_Symbol, PERIOD_${config.timeframe.toUpperCase()}, ${ind.params.period}, PRICE_CLOSE);`;
    if (ind.type === "MACD")
      return `   handle_macd = iMACD(_Symbol, PERIOD_${config.timeframe.toUpperCase()}, ${ind.params.fast}, ${ind.params.slow}, ${ind.params.signal}, PRICE_CLOSE);`;
    return "";
  })
  .join("\n")}
   
   return(INIT_SUCCEEDED);
}

//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
{
   // Reset daily PnL
   datetime currentDate = TimeCurrent();
   if(TimeDay(currentDate) != TimeDay(lastTradeDate))
   {
      dailyPnL = 0.0;
      lastTradeDate = currentDate;
   }
   
   // Check max daily loss
   if(dailyPnL <= -MaxDailyLoss)
   {
      Print("Max daily loss reached. Stopping trading for today.");
      return;
   }
   
   // Session filter
   if(!IsValidSession())
      return;
   
   // Entry logic
   if(CheckEntryConditions())
   {
      OpenTrade();
   }
}

//+------------------------------------------------------------------+
//| Check if current time is in valid trading session               |
//+------------------------------------------------------------------+
bool IsValidSession()
{
   MqlDateTime dt;
   TimeCurrent(dt);
   int hour = dt.hour;
   
${config.sessions
  .map((s) => {
    if (s === "london") return "   if(hour >= 8 && hour < 16) return true;";
    if (s === "newyork") return "   if(hour >= 13 && hour < 21) return true;";
    if (s === "overlap") return "   if(hour >= 13 && hour < 16) return true;";
    return "";
  })
  .join("\n")}
   
   return false;
}

//+------------------------------------------------------------------+
//| Check entry conditions                                           |
//+------------------------------------------------------------------+
bool CheckEntryConditions()
{
   // Add your specific entry logic here based on configured indicators
   // Example: EMA crossover, RSI levels, MACD histogram, etc.
   
   return false; // Placeholder - implement your logic
}

//+------------------------------------------------------------------+
//| Open trade with risk management                                  |
//+------------------------------------------------------------------+
void OpenTrade()
{
   double lotSize = CalculateLotSize();
   double stopLoss = StopLossPips * _Point * 10;
   double takeProfit = stopLoss * TakeProfitRatio;
   
   // Place order logic here
   // OrderSend(...);
}

//+------------------------------------------------------------------+
//| Calculate position size based on risk                           |
//+------------------------------------------------------------------+
double CalculateLotSize()
{
   double balance = AccountInfoDouble(ACCOUNT_BALANCE);
   double riskAmount = balance * (RiskPercent / 100.0);
   double stopLossPips = StopLossPips;
   double tickValue = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);
   
   double lotSize = riskAmount / (stopLossPips * tickValue * 10);
   return NormalizeDouble(lotSize, 2);
}
//+------------------------------------------------------------------+`;
  };

  const copyToClipboard = (code: string) => {
    navigator.clipboard.writeText(code);
    toast.success("Code copied to clipboard!");
  };

  const downloadCode = (code: string, filename: string) => {
    const blob = new Blob([code], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
    toast.success("Code downloaded!");
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-2 mb-4">
        <Code2 className="w-5 h-5 text-primary" />
        <h3 className="text-xl font-semibold">Export Strategy Code</h3>
      </div>

      <Card className="bg-secondary/30 border-border">
        <Tabs defaultValue="mql5" className="w-full">
          <TabsList className="w-full grid grid-cols-2 bg-background">
            <TabsTrigger value="mql5">MQL5 (MT5)</TabsTrigger>
            <TabsTrigger value="pine">Pine Script (TradingView)</TabsTrigger>
          </TabsList>

          <TabsContent value="mql5" className="p-0">
            <div className="relative">
              <div className="absolute top-4 right-4 flex gap-2 z-10">
                <Button
                  size="sm"
                  variant="secondary"
                  onClick={() => copyToClipboard(generateMQL5())}
                  className="profit-glow"
                >
                  <Copy className="w-4 h-4 mr-1" />
                  Copy
                </Button>
                <Button
                  size="sm"
                  variant="secondary"
                  onClick={() => downloadCode(generateMQL5(), "QuantumStrategy.mq5")}
                >
                  <Download className="w-4 h-4 mr-1" />
                  Download
                </Button>
              </div>
              <pre className="p-6 bg-background/50 rounded-lg overflow-x-auto text-xs font-mono max-h-[600px]">
                <code className="text-foreground">{generateMQL5()}</code>
              </pre>
            </div>
          </TabsContent>

          <TabsContent value="pine" className="p-6">
            <div className="bg-accent/10 border border-accent/30 rounded-lg p-4">
              <p className="text-accent text-sm">
                Pine Script export coming soon. The MQL5 version above contains the complete
                strategy logic that can be manually adapted to Pine Script for TradingView.
              </p>
            </div>
          </TabsContent>
        </Tabs>
      </Card>

      <Card className="p-6 bg-primary/5 border-primary/20">
        <h4 className="font-semibold mb-3 text-primary">Installation Instructions (MT5)</h4>
        <ol className="space-y-2 text-sm text-muted-foreground">
          <li>1. Copy the generated MQL5 code above</li>
          <li>2. Open MetaEditor (press F4 in MT5)</li>
          <li>3. File → New → Expert Advisor</li>
          <li>4. Paste the code and save as "QuantumStrategy.mq5"</li>
          <li>5. Click Compile (F7) - ensure no errors</li>
          <li>6. Drag the EA onto your chart</li>
          <li>7. Enable AutoTrading and configure inputs</li>
        </ol>
      </Card>
    </div>
  );
};
