"""
Advanced EA Generator
Assembles modular blocks into complete, production-quality EAs.
"""

from pathlib import Path
from dataclasses import dataclass, field
from typing import Optional
from datetime import datetime
import hashlib

from .base_ea import BaseEATemplate
from .indicators import IndicatorTemplates
from .risk_management import RiskManagementTemplates
from .trend_filters import TrendFilterTemplates
from .order_management import OrderManagementTemplates
from .filters import FilterTemplates
from .blocks.entry_blocks import EntryBlocks
from .blocks.exit_blocks import ExitBlocks
from .blocks.protection_blocks import ProtectionBlocks


@dataclass
class EAConfiguration:
    """Configuration for EA generation."""
    # Identification
    ea_name: str = "AdvancedEA"
    version: str = "1.00"
    description: str = "Production-quality trading robot"
    
    # Instruments
    instruments: list[str] = field(default_factory=lambda: ["EURUSD"])
    timeframe: str = "M5"
    
    # Entry settings
    use_trend_entry: bool = True
    use_pullback_entry: bool = True
    use_breakout_entry: bool = False
    use_reversal_entry: bool = False
    
    # Exit settings
    use_momentum_exit: bool = True
    use_atr_trailing: bool = True
    use_ma_trailing: bool = False
    use_time_exit: bool = True
    
    # Risk settings
    risk_percent: float = 1.0
    max_daily_loss_percent: float = 5.0
    max_daily_trades: int = 5
    max_open_trades: int = 1
    
    # Protection
    use_drawdown_guard: bool = True
    use_volatility_kill: bool = True
    use_news_kill: bool = True
    use_equity_protection: bool = True
    
    # Filters
    use_spread_filter: bool = True
    use_session_filter: bool = True
    use_mtf_filter: bool = True
    
    # Sessions
    trade_london: bool = True
    trade_newyork: bool = True
    trade_overlap: bool = True
    trade_asian: bool = False


class AdvancedEAGenerator:
    """
    Generates production-quality MQL5 EAs by assembling modular blocks.
    
    Features:
    - Multi-filter entry logic (≥2 trend filters + volatility + momentum)
    - Dual exit system (hard SL/TP + soft exits)
    - Prop-firm safe risk management
    - Protection layers (DD guard, kill switches)
    - MTF intelligence
    - Professional order handling
    """
    
    def __init__(self, config: EAConfiguration = None):
        self.config = config or EAConfiguration()
    
    def generate(self, strategy: dict = None) -> str:
        """
        Generate complete EA from configuration.
        
        Args:
            strategy: Optional strategy dict to override config
            
        Returns:
            Complete MQL5 source code
        """
        if strategy:
            self._apply_strategy(strategy)
        
        sections = [
            self._generate_header(),
            self._generate_enums(),
            self._generate_inputs(),
            self._generate_globals(),
            self._generate_on_init(),
            self._generate_on_deinit(),
            self._generate_on_tick(),
            self._generate_on_trade(),
            self._generate_entry_blocks(),
            self._generate_exit_blocks(),
            self._generate_protection_blocks(),
            self._generate_order_functions(),
            self._generate_helper_functions(),
        ]
        
        return "\n".join(sections)
    
    def _apply_strategy(self, strategy: dict):
        """Apply strategy dict to configuration."""
        if "instruments" in strategy:
            self.config.instruments = strategy["instruments"]
        if "timeframe" in strategy:
            self.config.timeframe = strategy["timeframe"]
        if "positionSizePercent" in strategy:
            self.config.risk_percent = strategy["positionSizePercent"]
        if "maxDailyLoss" in strategy:
            # Convert from fixed to percent if needed
            pass
    
    def _generate_magic_number(self) -> int:
        """Generate unique magic number from EA config."""
        hash_input = f"{self.config.ea_name}_{self.config.instruments}_{datetime.now().isoformat()}"
        hash_val = int(hashlib.md5(hash_input.encode()).hexdigest()[:8], 16)
        return hash_val % 1000000000  # Keep it reasonable
    
    def _generate_header(self) -> str:
        """Generate EA header with properties."""
        return f'''//+------------------------------------------------------------------+
//|                              {self.config.ea_name}.mq5              |
//|                       Advanced Production-Quality EA              |
//|                              Generated by QuantStride             |
//+------------------------------------------------------------------+
#property copyright "QuantStride Advanced Generator"
#property version   "{self.config.version}"
#property description "{self.config.description}"
#property description "Features: Multi-TF, Dual Exit, Prop-Firm Safe"
#property strict

#include <Trade\\Trade.mqh>
#include <Trade\\PositionInfo.mqh>
#include <Trade\\SymbolInfo.mqh>
'''
    
    def _generate_enums(self) -> str:
        """Generate custom enumerations."""
        return '''
//+------------------------------------------------------------------+
//|                         ENUMERATIONS                             |
//+------------------------------------------------------------------+
enum ENUM_MM_TYPE
{
   MM_FIXED = 0,           // Fixed lot size
   MM_PERCENT = 1,         // Percent of balance
   MM_AUTO = 2             // Auto-lot based on balance
};

enum ENUM_SIGNAL_TYPE
{
   SIGNAL_NONE = 0,
   SIGNAL_BUY = 1,
   SIGNAL_SELL = -1
};

enum ENUM_ENTRY_TYPE
{
   ENTRY_TREND = 0,
   ENTRY_PULLBACK = 1,
   ENTRY_BREAKOUT = 2,
   ENTRY_REVERSAL = 3
};

enum ENUM_EXIT_REASON
{
   EXIT_NONE = 0,
   EXIT_SL = 1,
   EXIT_TP = 2,
   EXIT_MOMENTUM = 3,
   EXIT_TRAILING = 4,
   EXIT_TIME = 5,
   EXIT_DD_GUARD = 6
};
'''
    
    def _generate_inputs(self) -> str:
        """Generate all input parameters."""
        magic = self._generate_magic_number()
        
        return f'''
//+------------------------------------------------------------------+
//|                         INPUT PARAMETERS                         |
//+------------------------------------------------------------------+

input group "=== General Settings ==="
input int MagicNumber = {magic};                             // Magic Number
input bool EnableLogging = true;                             // Enable Debug Logging

{EntryBlocks.generate_inputs()}

{ExitBlocks.generate_inputs()}

{ProtectionBlocks.generate_inputs()}

{FilterTemplates.generate_inputs()}

input group "=== Session Filter ==="
input bool UseSessionFilter = {'true' if self.config.use_session_filter else 'false'};
input bool TradeLondon = {'true' if self.config.trade_london else 'false'};
input bool TradeNewYork = {'true' if self.config.trade_newyork else 'false'};
input bool TradeLondonNYOverlap = {'true' if self.config.trade_overlap else 'false'};
input bool TradeAsian = {'true' if self.config.trade_asian else 'false'};
'''
    
    def _generate_globals(self) -> str:
        """Generate all global variables."""
        return f'''
//+------------------------------------------------------------------+
//|                       GLOBAL VARIABLES                           |
//+------------------------------------------------------------------+
CTrade trade;
CPositionInfo positionInfo;
CSymbolInfo symbolInfo;

double pipMultiplier = 1.0;
datetime lastTradeTime = 0;

// From entry blocks
{EntryBlocks.generate_globals()}

// From exit blocks
{ExitBlocks.generate_globals()}

// From protection blocks
{ProtectionBlocks.generate_globals()}
'''
    
    def _generate_on_init(self) -> str:
        """Generate OnInit function."""
        return f'''
//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
{{
   Print("==========================================");
   Print("Initializing {self.config.ea_name}...");
   Print("Instruments: {', '.join(self.config.instruments)}");
   Print("Timeframe: {self.config.timeframe}");
   Print("==========================================");
   
   // Initialize trade object
   trade.SetExpertMagicNumber(MagicNumber);
   trade.SetMarginMode();
   trade.SetTypeFillingBySymbol(_Symbol);
   trade.SetDeviationInPoints(MaxSlippagePoints);
   
   // Initialize symbol info
   if(!symbolInfo.Name(_Symbol))
   {{
      Print("Failed to initialize symbol info");
      return(INIT_FAILED);
   }}
   
   // Calculate pip multiplier
   int digits = (int)SymbolInfoInteger(_Symbol, SYMBOL_DIGITS);
   pipMultiplier = (digits == 3 || digits == 5) ? 10.0 : 1.0;
   
   // Handle synthetic indices
   string symbolName = _Symbol;
   if(StringFind(symbolName, "Volatility") >= 0 || 
      StringFind(symbolName, "Boom") >= 0 || 
      StringFind(symbolName, "Crash") >= 0 ||
      StringFind(symbolName, "Step") >= 0 ||
      StringFind(symbolName, "Jump") >= 0)
   {{
      pipMultiplier = 1.0;
   }}
   
   Print("Pip Multiplier: ", pipMultiplier);
   
   // Initialize entry indicators
   if(!InitEntryIndicators())
   {{
      Print("Failed to initialize entry indicators");
      return(INIT_FAILED);
   }}
   
   // Initialize exit indicators
   if(!InitExitIndicators())
   {{
      Print("Failed to initialize exit indicators");
      return(INIT_FAILED);
   }}
   
   // Initialize protection systems
   if(!InitProtection())
   {{
      Print("Failed to initialize protection systems");
      return(INIT_FAILED);
   }}
   
   Print("{self.config.ea_name} initialized successfully!");
   Print("==========================================");
   return(INIT_SUCCEEDED);
}}
'''
    
    def _generate_on_deinit(self) -> str:
        """Generate OnDeinit function."""
        return f'''
//+------------------------------------------------------------------+
//| Expert deinitialization function                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{{
   // Release entry indicators
   DeinitEntryIndicators();
   
   // Release exit indicators
   DeinitExitIndicators();
   
   Print("{self.config.ea_name} deinitialized. Reason: ", reason);
   Print("Final Daily PnL: $", DoubleToString(dailyPnL, 2));
   Print("Total trades today: ", dailyTradeCount);
}}
'''
    
    def _generate_on_tick(self) -> str:
        """Generate OnTick function."""
        return '''
//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
{
   // Run protection checks first
   RunProtectionChecks();
   
   // Skip if halted
   if(drawdownHalt)
      return;
   
   // Manage existing positions
   ManageOpenPositions();
   
   // Only check for new entries on new bar
   static datetime lastBarTime = 0;
   datetime currentBarTime = iTime(_Symbol, PERIOD_CURRENT, 0);
   
   if(currentBarTime == lastBarTime)
      return;
   lastBarTime = currentBarTime;
   
   // Check all filters before entry
   if(!PassesAllFilters())
      return;
   
   // Check if we can open a new trade
   ENUM_SIGNAL_TYPE signal = CheckEntryConditions();
   
   if(signal == SIGNAL_NONE)
      return;
   
   int direction = (signal == SIGNAL_BUY) ? 1 : -1;
   
   if(!CanOpenNewTrade(direction))
      return;
   
   // Calculate SL/TP
   ENUM_ORDER_TYPE orderType = (signal == SIGNAL_BUY) ? ORDER_TYPE_BUY : ORDER_TYPE_SELL;
   double sl = CalculateStopLoss(orderType);
   double sl_pips = (signal == SIGNAL_BUY) ? 
      (symbolInfo.Ask() - sl) / (pipMultiplier * _Point) :
      (sl - symbolInfo.Bid()) / (pipMultiplier * _Point);
   double tp = CalculateTakeProfit(orderType, sl_pips);
   double lots = CalculateLotSize(sl_pips);
   
   // Execute trade
   bool success = false;
   if(signal == SIGNAL_BUY)
   {
      success = OpenBuyOrder(lots, sl_pips, sl_pips * TakeProfitRatio, "Trend Entry");
   }
   else if(signal == SIGNAL_SELL)
   {
      success = OpenSellOrder(lots, sl_pips, sl_pips * TakeProfitRatio, "Trend Entry");
   }
   
   if(success)
   {
      OnTradeOpened(direction);
   }
}
'''
    
    def _generate_on_trade(self) -> str:
        """Generate OnTrade function."""
        return '''
//+------------------------------------------------------------------+
//| Trade event handler                                              |
//+------------------------------------------------------------------+
void OnTrade()
{
   static int lastPositionCount = 0;
   int currentPositionCount = PositionsTotal();
   
   if(currentPositionCount < lastPositionCount)
   {
      // A position was closed - update stats
      UpdateDailyStats();
   }
   
   lastPositionCount = currentPositionCount;
}

void UpdateDailyStats()
{
   // Get today's start time
   MqlDateTime today;
   TimeToStruct(TimeCurrent(), today);
   today.hour = 0;
   today.min = 0;
   today.sec = 0;
   datetime dayStart = StructToTime(today);
   
   // Calculate profit from today's closed deals
   dailyPnL = 0.0;
   HistorySelect(dayStart, TimeCurrent());
   
   for(int i = HistoryDealsTotal() - 1; i >= 0; i--)
   {
      ulong ticket = HistoryDealGetTicket(i);
      if(ticket > 0)
      {
         if(HistoryDealGetInteger(ticket, DEAL_MAGIC) == MagicNumber &&
            HistoryDealGetString(ticket, DEAL_SYMBOL) == _Symbol)
         {
            double profit = HistoryDealGetDouble(ticket, DEAL_PROFIT);
            dailyPnL += profit;
            
            // Update consecutive counts
            if(profit > 0)
            {
               consecutiveWins++;
               consecutiveLosses = 0;
            }
            else if(profit < 0)
            {
               consecutiveLosses++;
               consecutiveWins = 0;
            }
         }
      }
   }
}
'''
    
    def _generate_entry_blocks(self) -> str:
        """Generate entry block functions."""
        return f'''
{EntryBlocks.generate_init()}

{EntryBlocks.generate_deinit()}

{EntryBlocks.generate_trend_detection()}

{EntryBlocks.generate_volatility_check()}

{EntryBlocks.generate_momentum_check()}

{EntryBlocks.generate_trend_entry()}

{EntryBlocks.generate_pullback_entry()}

{EntryBlocks.generate_breakout_entry()}

{EntryBlocks.generate_reversal_entry()}

{EntryBlocks.generate_master_entry_check()}
'''
    
    def _generate_exit_blocks(self) -> str:
        """Generate exit block functions."""
        return f'''
{ExitBlocks.generate_init()}

{ExitBlocks.generate_deinit()}

{ExitBlocks.generate_calculate_sl_tp()}

{ExitBlocks.generate_momentum_exit()}

{ExitBlocks.generate_atr_trailing()}

{ExitBlocks.generate_ma_trailing()}

{ExitBlocks.generate_time_exit()}

{ExitBlocks.generate_manage_exits()}
'''
    
    def _generate_protection_blocks(self) -> str:
        """Generate protection block functions."""
        return f'''
{ProtectionBlocks.generate_init()}

{ProtectionBlocks.generate_drawdown_guard()}

{ProtectionBlocks.generate_position_limits()}

{ProtectionBlocks.generate_volatility_kill_switch()}

{ProtectionBlocks.generate_news_kill_switch()}

{ProtectionBlocks.generate_equity_protection()}

{ProtectionBlocks.generate_master_kill_check()}
'''
    
    def _generate_order_functions(self) -> str:
        """Generate order management functions."""
        return OrderManagementTemplates.generate_safe_order_open()
    
    def _generate_helper_functions(self) -> str:
        """Generate helper utility functions."""
        return '''
//+------------------------------------------------------------------+
//|                       HELPER FUNCTIONS                           |
//+------------------------------------------------------------------+

//--- Log message with timestamp
void LogMessage(string message)
{
   if(EnableLogging)
   {
      Print(TimeToString(TimeCurrent(), TIME_DATE|TIME_MINUTES), " | ", message);
   }
}

//--- Check if we have an open position
bool HasOpenPosition()
{
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      if(positionInfo.SelectByIndex(i))
      {
         if(positionInfo.Symbol() == _Symbol && positionInfo.Magic() == MagicNumber)
            return true;
      }
   }
   return false;
}

//--- Calculate lot size
double CalculateLotSize(double slPips)
{
   double balance = AccountInfoDouble(ACCOUNT_BALANCE);
   double riskAmount = balance * (RiskPercent / 100.0);
   
   double tickValue = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);
   double tickSize = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);
   double lotStep = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP);
   double minLot = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN);
   double maxLot = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX);
   
   double pointValue = (tickValue / tickSize) * _Point;
   
   double lots = 0.0;
   if(pointValue > 0 && slPips > 0)
   {
      double slPoints = slPips * pipMultiplier;
      lots = riskAmount / (slPoints * pointValue);
   }
   
   lots = MathFloor(lots / lotStep) * lotStep;
   lots = MathMax(minLot, MathMin(maxLot, lots));
   
   return lots;
}

//--- Combined filter check
bool PassesAllFilters()
{
   // Session filter
   if(UseSessionFilter && !IsValidSession())
   {
      if(EnableLogging) Print("Blocked by session filter");
      return false;
   }
   
   // Spread filter
   if(!IsSpreadAcceptable())
   {
      return false;
   }
   
   // News filter
   if(!IsNewsKillClear())
   {
      return false;
   }
   
   // Volatility kill switch
   if(!IsVolatilityKillClear())
   {
      return false;
   }
   
   // Drawdown check
   if(!IsDrawdownSafe())
   {
      return false;
   }
   
   return true;
}

''' + FilterTemplates.generate_session_filter() + '''

''' + FilterTemplates.generate_spread_filter()
    
    def save_to_file(self, output_dir: str = None) -> str:
        """Save generated EA to file."""
        code = self.generate()
        
        if output_dir:
            output_path = Path(output_dir) / f"{self.config.ea_name}.mq5"
        else:
            output_path = Path(f"{self.config.ea_name}.mq5")
        
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(code, encoding="utf-8")
        
        return str(output_path)
