"""
Base EA Template
Core skeleton for MQL5 Expert Advisors.
"""


class BaseEATemplate:
    """
    Generates the base MQL5 EA structure.
    
    Includes:
    - Property declarations
    - OnInit, OnTick, OnDeinit, OnTrade functions
    - Error handling framework
    - Logging system
    - Magic number management
    """
    
    @staticmethod
    def generate_header(
        ea_name: str = "GeneratedEA",
        version: str = "1.00",
        description: str = "Auto-generated Expert Advisor",
        copyright_holder: str = "QuantStride"
    ) -> str:
        """Generate EA header with properties."""
        return f'''//+------------------------------------------------------------------+
//|                                          {ea_name}.mq5           |
//|                              Auto-Generated by QuantStride       |
//+------------------------------------------------------------------+
#property copyright "{copyright_holder}"
#property version   "{version}"
#property description "{description}"
#property strict

#include <Trade\\Trade.mqh>
#include <Trade\\PositionInfo.mqh>
#include <Trade\\SymbolInfo.mqh>
'''

    @staticmethod
    def generate_enums() -> str:
        """Generate custom enumerations."""
        return '''
//+------------------------------------------------------------------+
//|                         ENUMERATIONS                             |
//+------------------------------------------------------------------+
enum ENUM_MM_TYPE
{
   MM_FIXED = 0,           // Fixed lot size
   MM_PERCENT = 1,         // Percent of balance
   MM_MARTINGALE = 2,      // Martingale (double after loss)
   MM_ANTI_MARTINGALE = 3  // Anti-Martingale (double after win)
};

enum ENUM_SIGNAL_TYPE
{
   SIGNAL_NONE = 0,
   SIGNAL_BUY = 1,
   SIGNAL_SELL = -1
};

enum ENUM_EXIT_REASON
{
   EXIT_NONE = 0,
   EXIT_SL = 1,
   EXIT_TP = 2,
   EXIT_SIGNAL = 3,
   EXIT_MANUAL = 4,
   EXIT_DAILY_LIMIT = 5
};
'''

    @staticmethod
    def generate_inputs(
        risk_percent: float = 1.0,
        sl_pips: float = 20.0,
        tp_ratio: float = 2.0,
        magic_number: int = 12345,
        max_daily_loss: float = 100.0,
        max_daily_trades: int = 10
    ) -> str:
        """Generate input parameters."""
        return f'''
//+------------------------------------------------------------------+
//|                         INPUT PARAMETERS                         |
//+------------------------------------------------------------------+
input group "=== Risk Management ==="
input double RiskPercent = {risk_percent};                   // Risk per trade (%)
input double StopLossPips = {sl_pips};                       // Stop Loss (pips)
input double TakeProfitRatio = {tp_ratio};                   // Take Profit Ratio (R:R)
input ENUM_MM_TYPE MoneyManagement = MM_PERCENT;             // Money Management Type

input group "=== Daily Limits ==="
input double MaxDailyLoss = {max_daily_loss};                // Max Daily Loss ($)
input int MaxDailyTrades = {max_daily_trades};               // Max Daily Trades

input group "=== Breakeven & Trailing ==="
input bool UseBreakeven = true;                              // Enable Breakeven
input double BreakevenPips = 10.0;                           // Breakeven activation (pips)
input bool UseTrailingStop = true;                           // Enable Trailing Stop
input double TrailingDistance = 15.0;                        // Trailing distance (pips)
input double TrailingActivation = 20.0;                      // Trailing activation (pips)

input group "=== General Settings ==="
input int MagicNumber = {magic_number};                      // Magic Number
input int MaxSlippage = 3;                                   // Max Slippage (points)
input bool EnableLogging = true;                             // Enable Debug Logging
'''

    @staticmethod
    def generate_globals() -> str:
        """Generate global variables."""
        return '''
//+------------------------------------------------------------------+
//|                       GLOBAL VARIABLES                           |
//+------------------------------------------------------------------+
CTrade trade;
CPositionInfo positionInfo;
CSymbolInfo symbolInfo;

double dailyPnL = 0.0;
int dailyTradeCount = 0;
datetime lastTradeDate;
bool dailyLimitReached = false;
double pipMultiplier = 1.0;

// Trade tracking
int consecutiveLosses = 0;
int consecutiveWins = 0;
double lastLotSize = 0.0;
bool breakevenApplied = false;
'''

    @staticmethod
    def generate_on_init(indicator_init: str = "") -> str:
        """Generate OnInit function."""
        return f'''
//+------------------------------------------------------------------+
//| Expert initialization function                                   |
//+------------------------------------------------------------------+
int OnInit()
{{
   Print("===========================================");
   Print("Initializing EA...");
   
   // Initialize trade object
   trade.SetExpertMagicNumber(MagicNumber);
   trade.SetMarginMode();
   trade.SetTypeFillingBySymbol(_Symbol);
   trade.SetDeviationInPoints(MaxSlippage);
   
   // Initialize symbol info
   if(!symbolInfo.Name(_Symbol))
   {{
      Print("Failed to initialize symbol info");
      return(INIT_FAILED);
   }}
   
   // Calculate pip multiplier
   int digits = (int)SymbolInfoInteger(_Symbol, SYMBOL_DIGITS);
   pipMultiplier = (digits == 3 || digits == 5) ? 10.0 : 1.0;
   
   // Check for synthetic indices
   string symbolName = _Symbol;
   if(StringFind(symbolName, "Volatility") >= 0 || 
      StringFind(symbolName, "Boom") >= 0 || 
      StringFind(symbolName, "Crash") >= 0)
   {{
      pipMultiplier = 1.0;  // Synthetics use 1 pip = 1 point
   }}
   
   Print("Pip Multiplier: ", pipMultiplier);
   
   // Initialize date tracking
   lastTradeDate = TimeCurrent();
   
   // Initialize indicators
{indicator_init}
   
   Print("EA initialized successfully");
   Print("===========================================");
   return(INIT_SUCCEEDED);
}}
'''

    @staticmethod
    def generate_on_deinit(cleanup_code: str = "") -> str:
        """Generate OnDeinit function."""
        return f'''
//+------------------------------------------------------------------+
//| Expert deinitialization function                                 |
//+------------------------------------------------------------------+
void OnDeinit(const int reason)
{{
   // Release indicator handles
{cleanup_code}
   
   Print("EA deinitialized. Reason: ", reason);
   Print("Final Daily PnL: $", DoubleToString(dailyPnL, 2));
}}
'''

    @staticmethod
    def generate_on_tick(tick_logic: str = "") -> str:
        """Generate OnTick function."""
        return f'''
//+------------------------------------------------------------------+
//| Expert tick function                                             |
//+------------------------------------------------------------------+
void OnTick()
{{
   // Reset daily stats on new day
   CheckNewDay();
   
   // Check daily limits
   if(dailyLimitReached)
      return;
   
   // Manage existing positions
   ManageOpenPositions();
   
   // Only check for new entries on new bar
   static datetime lastBarTime = 0;
   datetime currentBarTime = iTime(_Symbol, PERIOD_CURRENT, 0);
   
   if(currentBarTime == lastBarTime)
      return;
   lastBarTime = currentBarTime;
   
   // Skip if we already have a position
   if(HasOpenPosition())
      return;
   
   // Check entry conditions
{tick_logic}
}}
'''

    @staticmethod
    def generate_on_trade() -> str:
        """Generate OnTrade function for position tracking."""
        return '''
//+------------------------------------------------------------------+
//| Trade event handler                                              |
//+------------------------------------------------------------------+
void OnTrade()
{
   // Check for closed positions and update statistics
   static int lastPositionCount = 0;
   int currentPositionCount = PositionsTotal();
   
   if(currentPositionCount < lastPositionCount)
   {
      // A position was closed - update daily PnL
      UpdateDailyPnL();
   }
   
   lastPositionCount = currentPositionCount;
}
'''

    @staticmethod
    def generate_helper_functions() -> str:
        """Generate helper utility functions."""
        return '''
//+------------------------------------------------------------------+
//|                       HELPER FUNCTIONS                           |
//+------------------------------------------------------------------+

//--- Check if we have an open position with our magic number
bool HasOpenPosition()
{
   for(int i = PositionsTotal() - 1; i >= 0; i--)
   {
      if(positionInfo.SelectByIndex(i))
      {
         if(positionInfo.Symbol() == _Symbol && positionInfo.Magic() == MagicNumber)
            return true;
      }
   }
   return false;
}

//--- Check for new trading day
void CheckNewDay()
{
   MqlDateTime currentTime, lastTime;
   TimeToStruct(TimeCurrent(), currentTime);
   TimeToStruct(lastTradeDate, lastTime);
   
   if(currentTime.day != lastTime.day || 
      currentTime.mon != lastTime.mon || 
      currentTime.year != lastTime.year)
   {
      // New day - reset counters
      dailyPnL = 0.0;
      dailyTradeCount = 0;
      dailyLimitReached = false;
      lastTradeDate = TimeCurrent();
      if(EnableLogging) Print("=== NEW TRADING DAY ===");
   }
}

//--- Update daily PnL from closed positions
void UpdateDailyPnL()
{
   // Get today's start time
   MqlDateTime today;
   TimeToStruct(TimeCurrent(), today);
   today.hour = 0;
   today.min = 0;
   today.sec = 0;
   datetime dayStart = StructToTime(today);
   
   // Calculate profit from today's closed deals
   dailyPnL = 0.0;
   HistorySelect(dayStart, TimeCurrent());
   
   for(int i = HistoryDealsTotal() - 1; i >= 0; i--)
   {
      ulong ticket = HistoryDealGetTicket(i);
      if(ticket > 0)
      {
         if(HistoryDealGetInteger(ticket, DEAL_MAGIC) == MagicNumber &&
            HistoryDealGetString(ticket, DEAL_SYMBOL) == _Symbol)
         {
            dailyPnL += HistoryDealGetDouble(ticket, DEAL_PROFIT);
         }
      }
   }
   
   // Check daily loss limit
   if(dailyPnL <= -MaxDailyLoss)
   {
      dailyLimitReached = true;
      if(EnableLogging) Print("DAILY LOSS LIMIT REACHED: $", DoubleToString(dailyPnL, 2));
   }
   
   // Check daily trade limit
   if(dailyTradeCount >= MaxDailyTrades)
   {
      dailyLimitReached = true;
      if(EnableLogging) Print("DAILY TRADE LIMIT REACHED: ", dailyTradeCount);
   }
}

//--- Calculate lot size based on money management
double CalculateLotSize(double slPips)
{
   double balance = AccountInfoDouble(ACCOUNT_BALANCE);
   double riskAmount = balance * (RiskPercent / 100.0);
   
   double tickValue = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_VALUE);
   double tickSize = SymbolInfoDouble(_Symbol, SYMBOL_TRADE_TICK_SIZE);
   double lotStep = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_STEP);
   double minLot = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MIN);
   double maxLot = SymbolInfoDouble(_Symbol, SYMBOL_VOLUME_MAX);
   
   // Calculate points for SL
   double slPoints = slPips * pipMultiplier * _Point;
   double pointValue = tickValue / tickSize * _Point;
   
   // Calculate lot size
   double lots = 0.0;
   if(pointValue > 0 && slPips > 0)
   {
      lots = riskAmount / (slPips * pipMultiplier * pointValue);
   }
   
   // Apply money management modifications
   if(MoneyManagement == MM_MARTINGALE && consecutiveLosses > 0)
   {
      lots *= MathPow(2, MathMin(consecutiveLosses, 3));
   }
   else if(MoneyManagement == MM_ANTI_MARTINGALE && consecutiveWins > 0)
   {
      lots *= MathPow(2, MathMin(consecutiveWins, 3));
   }
   
   // Normalize lot size
   lots = MathFloor(lots / lotStep) * lotStep;
   lots = MathMax(minLot, MathMin(maxLot, lots));
   
   lastLotSize = lots;
   return lots;
}

//--- Log message with timestamp
void LogMessage(string message)
{
   if(EnableLogging)
   {
      Print(TimeToString(TimeCurrent(), TIME_DATE|TIME_MINUTES), " | ", message);
   }
}
'''

    @classmethod
    def generate_full_skeleton(
        cls,
        ea_name: str = "QuantStrideEA",
        indicator_init: str = "",
        cleanup_code: str = "",
        tick_logic: str = ""
    ) -> str:
        """Generate complete EA skeleton."""
        return (
            cls.generate_header(ea_name) +
            cls.generate_enums() +
            cls.generate_inputs() +
            cls.generate_globals() +
            cls.generate_on_init(indicator_init) +
            cls.generate_on_deinit(cleanup_code) +
            cls.generate_on_tick(tick_logic) +
            cls.generate_on_trade() +
            cls.generate_helper_functions()
        )
